### ISSUE TITLE
ボタンの折り返し

### ISSUE THREAD

**Issue by YoshitoAoki** [c0a21162/ProjExD#3]
https://github.com/c0a21162/ProjExD/blob/fc9f4f9251185cec45276c7825d70bc575985cac/ex02/calc.py#L77
ボタン数が多くなって”＝”のボタンが下に行っちゃってるみたいだから、if文の追加でrowの値が一定以上になったら上になるように戻してcolumnを1増やすとかするといいかも。
具体的なコード思いついてないから、抽象的でごめんね

**Comment by c0a21162** [comment]
"operators"の"r"を1に、deleterの"c"を1に変更したので"="の位置が"."の隣になりました!
コメントありがとう！
