### ISSUE TITLE
不必要なメモ書き

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21162/ProjExD#4]
https://github.com/c0a21162/ProjExD/blob/001135c372c9ff47592b00a13bfb6f183eb64076/ex02/calc.py#L31

特に使わないメモは消してしまった方が行数も減ってスッキリするかも。
20、21行目とか41、42行目は空欄空けすぎかな。

**Comment by c0a21162** [comment]
31行目は授業内でやったことなので残してます！
空欄はつめました！コメントありがとう！
