### ISSUE TITLE
不必要なコメント文

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21162/ProjExD#5]
https://github.com/c0a21162/ProjExD/blob/2dd1c0f0ea01b99f5adc52426b836967cdd90b7f/ex03/maze.py#L60

実現出来なかった部分をコメント文にするのは今後の参考にもなるので良いと思います！
ただ、実際に使わないコードは消してしまった方が行数も減り見やすくなるのではないでしょうか。

**Comment by c0a21162** [comment]
確かにそうだね...
変更しました！コメントありがとう！
