### ISSUE TITLE
移動を遅くする

### ISSUE THREAD

**Issue by YoshitoAoki** [c0a21162/ProjExD#6]
https://github.com/c0a21162/ProjExD/blob/2dd1c0f0ea01b99f5adc52426b836967cdd90b7f/ex03/maze.py#L46
この場所の100って入っている値を500とかにすると移動は少し遅くなるけど、早すぎて色が変わらないのなくなるかも

**Comment by c0a21162** [comment]
500にすると全然移動しなくなっちゃうからこのままにします！
コメントありがとう！
