### ISSUE TITLE
if文をまとめる

### ISSUE THREAD

**Issue by yuma-kishimoto** [c0a21162/ProjExD#7]
https://github.com/c0a21162/ProjExD/blob/33063f19b13cd7475d26ce1597885d41d291e33a/ex04/dodge_bomb.py#L118

104~116行目と118~130行目が一緒のようなので、104行目に　or を使用して
まとめる事ができると思います。

**Comment by c0a21162** [comment]
orでまとめてコードを減らしました！
コメントありがとう！
