### ISSUE TITLE
音楽停止or追加

### ISSUE THREAD

**Issue by YoshitoAoki** [c0a21162/ProjExD#8]
https://github.com/c0a21162/ProjExD/blob/33063f19b13cd7475d26ce1597885d41d291e33a/ex04/dodge_bomb.py#L104
爆弾に当たっちゃったときに音楽を停止するか、悲しい感じの音楽にするとよりいいかも

**Comment by c0a21162** [comment]
if tori_rct.colliderect(bomb_rct) or tori_rct.colliderect(bomb_rct2):
の中に
pg.mixer.music.stop()
を追加してこうかとんと爆弾が当たったときに音楽を止めるようにしました！
コメントありがとう！
